{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | quote }}
  annotations:
{{- range $k, $v := .Values.serviceAccount.annotations }}
    {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
