trigger:
  branches:
    include:
      - main
      - develop
      - feature/*
pr:
  branches:
    include:
      - main
      - develop
      - feature/*

stages:
  # --- Validation for PRs and branches ---
  - stage: Validate
    condition: ne(startsWith(variables['Build.SourceBranch'], 'refs/tags/'), true)
    jobs:
      - job: Validate
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - script: |
              set -e
              make ci
            displayName: "Run Terraform CI (PR/Branch)"

  # --- Release stage for tags ---
  - stage: Release
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - script: |
              set -e
              make ci
            displayName: "Run Terraform CI (Release)"

          # Inside the Release stage, after make ci
          - script: |
              git config user.email "ci-bot@halomd.com"
              git config user.name "CI Bot"

              # Add generated files
              git add MODULES.md CHANGELOG.md modules/*/README.auto.md

              if ! git diff --cached --quiet; then
                git commit -m "chore: update docs and changelog for $(Build.SourceBranchName)"
                git push origin HEAD:main
              else
                echo "No changes to commit."
              fi
            displayName: "Commit and Push Updates (Release)"

