{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "edr-agent.fullname" .) .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: edr-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
