apiVersion: v2
name: flask-app
description: A lightweight Helm chart for deploying Flask web applications on AKS with AGIC and autoscaling options.
type: application
version: 0.1.0
appVersion: "1.0.0"
