apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-webapp.fullname" . }}
  labels:
    {{- include "python-webapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "python-webapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ ternary .Values.service.targetPort.fastapi (ternary .Values.service.targetPort.flask .Values.service.targetPort.custom (eq .Values.framework "flask")) (eq .Values.framework "fastapi") }}
