{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "python-webapp.fullname" . }}
  labels:
    {{- include "python-webapp.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ include "python-webapp.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy }}
{{- end }}
